---
# tasks file for db-tier
#
- name: deploy postgres
  hosts: apps
  gather_facts: false
  become: true
  hosts: appdbs
  tasks:
  - name: install progress
    command: yum install -y postgresql-server

  - name: enable postgresql at boot
    service:
      name: postgresql
      enabled: yes
  - name: tell user to finish setting up postgres
    debug:
      msg: Either uncomment the postgres setup or manually login and initialize


  only run the next 2 tasks once!
  - name: initilize postgres
    command: postgresql-setup initdb
    register: r_postgres_init
    failed_when: >-
      r_postgres_init.rc != 0 and
      r_postgres_init.stdout != 'Data directory is not empty!'

  - name: start postgres
    service:
      name: postgresql.service
      state: started
