---
# tasks file for db-tier
- name: install {{ db-app }}
  command: yum install -y "{[ db-app }}"

- name: enable {{ db-app }} at boot
  service:
    name: "{{ db-service }}"
    enabled: yes

- name: Check if postgresql has been initialised
  stat:
    path: /var/lib/pgsql/data/PG_VERSION
  register: postgresql_initdb

- name: initilize {{ db-app }}
  command: postgresql-setup initdb
  when: postgresql_initdb.stat.exists == false
  register: r_postgres_init
  failed_when: >-
    r_postgres_init.rc != 0 and
    r_postgres_init.stdout != 'Data directory is not empty!'

- name: start {{ db-service }}
  service:
    name: "{{ db-service }}"
    state: started

  
