---
# tasks file for app-tier
  - name: install {{ service }}
    package:
      name: "{{ service }}"
      state: latest
      
  - name: enable {{ service }} at boot
    service:
      name: tomcat
      enabled: yes
      
  - name: create Document ROOT tomcat directory
    file:
      path: "{{ tomcat_web_root }}"
      state: directory
      
  - name: Write webapps/ROOT/index.html
    template:
      src: index.html.j2
      dest: "{{ tomcat_web_root }}/index.html"
      mode: 0644
      
  - name: start tomcat
    service:
      name: tomcat
      state: restarted